channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - cmake=3.26.3
  - gperftools=2.10
  - numpy=1.25.2
  - ninja=1.10.2
  - pyyaml=6.0
  - setuptools=68.0.0
  - cffi=1.15.1
  - typing_extensions=4.7.1
  - future=0.18.3
  - six=1.16.0
  - requests=2.31.0
  - dataclasses=0.8
  - psutil=5.9.0
  - chardet
  - pip
  - pip:
      - absl-py==1.4.0
      - tqdm==4.65.0
      - onnx==1.14.0
      - lark-parser==0.12.0
      - hypothesis==6.82.0
      - pyre-extensions==0.0.30
      - scikit-learn==1.3.0
      - pybind11==2.11.1
      - mlperf-logging @ git+https://github.com/mlperf/logging@3.0.0-rc2
      - iopath @ git+https://github.com/facebookresearch/iopath
      - tensordict==0.1.2
      - torchsnapshot==0.1.0
      - fbgemm_gpu==1.1.0
      - torchrec==1.1.0
      - numpy==1.25.2
      - --extra-index-url https://download.pytorch.org/whl/cpu
